# Generated by Django 5.2 on 2025-04-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=50)),
                ('stock_min', models.IntegerField()),
                ('stock_max', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
